import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
const root=path.resolve(new URL('..',import.meta.url).pathname);
process.env.NEWS_AUDIT_EXPORT='1';
const require=createRequire(import.meta.url);
const news=require(path.join(root,'api','news.js'));
const a=news.__audit;
const assert=(x,m)=>{if(!x)throw new Error(m)};
assert(a.LOCALE_RESULT_HINTS.NPB?.includes('試合終了'),'NPB locale result hints missing');
assert(a.LOCALE_RESULT_HINTS.KBO?.includes('경기결과'),'KBO locale result hints missing');
assert(a.localeResultSignal('巨人が阪神に勝利、試合終了','NPB'),'NPB Japanese result signal failed');
assert(a.classify('巨人が阪神に勝利、試合終了',{league:'NPB'}).includes('比賽結果'),'NPB result classification failed');
const key=a.cacheKey({sport:'冰球',league:'NHL',contentTypes:['全部'],hours:24});
assert(key.includes('"cacheVersion":"v4"'),'cache key missing v3');
assert(fs.existsSync(path.join(root,'manifest.json')),'PWA manifest missing');
assert(fs.existsSync(path.join(root,'sw.js')),'service worker missing');
assert(fs.existsSync(path.join(root,'api','health.js')),'health endpoint missing');
assert(fs.existsSync(path.join(root,'api','cron.js')),'cron endpoint missing');
assert(fs.existsSync(path.join(root,'api','lib','redis.js')),'redis adapter missing');
assert(fs.existsSync(path.join(root,'api','lib','rate-limit.js')),'rate limit adapter missing');
const vercel=JSON.parse(fs.readFileSync(path.join(root,'vercel.json'),'utf8'));
assert(!Array.isArray(vercel.crons),'Vercel Hobby 不應使用高頻 Cron');
assert(fs.existsSync(path.join(root,'.github','workflows','sports-cron.yml')),'external cron workflow missing');
assert(a.validateContractPayload({items:[],count:0,errors:[],fetchedAt:new Date().toISOString()}).ok,'contract empty payload failed');
const health=await a.healthSnapshot();
assert(typeof health==='object' && health.version==='health-v4','health snapshot failed');
console.log('PASS：v3 locale hints、cache version、PWA、health、external cron、rate limit 與 Redis fallback structure checks 通過。');
